export enum ColorsEnum {
  Pelorous = '#3FADB5',
  Amulet = '#87A980',
  Casper = '#A6BBCF',
  GreenSmoke = '#AAAA66',
  Silver = '#C0C0C0',
  Spindle = '#C0DEED',
  Celadon = '#C7E9C0',
  LemonChiffon = '#D7D7A0',
  Pastel = '#D8BFD8',
  BurlyWood = '#DAC4B4',
  Calico = '#DEB887',
  Golden = '#DEBD5C',
  Gold = '#E2D96E',
  Parchment = '#E6E0F8',
  Beige = '#E7E7AE',
  RosyBrown = '#E9967A',
  Pink = '#F3B567',
  LightSalmon = '#FDD0A2',
  Honeydew = '#FDF0C2',
  Cornflower = '#FFAAAA',
  LightCoral = '#FFCC66',
  Chablis = '#FFF0F0',
  White = '#FFFFFF',
}
