name: Check branch name

on:
  push:
    branches: [ main ]

permissions:
  contents: write

#jobs:
#
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: 'Automated Version Bump'
#        uses: 'phips28/gh-action-bump-version@master'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          minor-wording: 'add,Adds,new,added'
#          major-wording: 'MAJOR,cut-major'
#          patch-wording: 'patch,fixes,fixed,fix'
#          rc-wording: 'RELEASE,alpha'
#          commit-message: 'CI: bumps version to {{version}} [skip ci]'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun index.ts
      - run: bun run build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            package.json
            dist
